### ISSUE TITLE
Sourcing `configure-openvpn.sh` overides environment variables, causing issues with `PWD` in vyprvpn.

### ISSUE THREAD

**Issue by MayeulC** [haugene/docker-transmission-openvpn#1615]
Thanks a bunch to @clement-z who helped me debug this, it would have been much longer without his help.

## Describe the problem

Sourcing `"$VPN_PROVIDER_HOME"/configure-openvpn.sh` can override environment variables from parent script, causing issues.

This is the incriminating line:
https://github.com/haugene/docker-transmission-openvpn/blob/a4d65774f855a04070766e53346661f48c76fa0e/openvpn/start.sh#L64

More specifically, vyprvpn [changes the current directory](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/vyprvpn/configure-openvpn.sh#L27), then [deletes it](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/vyprvpn/configure-openvpn.sh#L52). This causes the rest of `start.sh` to execute in a no-longer-existing directory, and output things like

> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

## Proposed solutions

1. The obvious fix is to remove `cd` calls from the VYPRVPN and any other `configure-openvpn.sh` files. PR in #1616
2. Check if the issue is present for other providers
3. Stop sourcing that file. This is obviously quite dangerous as seen presently, and could lead to a lot of other bugs. I propose adding an interface to specify environment variables explicitly:
  * It could be an `.env` file like for transmission.
  * Quite complex, though not that hard to read if using bash functions, environment variables could be echoed in [another file descriptor](http://mywiki.wooledge.org/BashFAQ/002) to be passed back to the caller separately: `exec 42>&1; export $( "$VPN_PROVIDER_HOME"/configure-openvpn.sh 3>&1 1>&42 ); exec 42>&-` while in the `sh` file: `echo MYVAR=foo >&3`.
  * Use another programming language to pass things around?

Obviously 2. isn't strictly necessary, but it would be better in my opinion.

## Add your docker run command or docker-compose file
Basically a very simple
```
docker run --cap-add=NET_ADMIN -d \
      --name transmission-openvpn \
      -e OPENVPN_PROVIDER=VYPRVPN \
      -e OPENVPN_USERNAME="username" \
      -e OPENVPN_PASSWORD="password" \
      haugene/transmission-openvpn:latest
```
Is enough. settings.json doesn't get generated correctly (as the python script crashes), and stores downloads in `/root/Downloads`... Note that this obviously happens for the first time only with VYPRVPN.

### Note:
I didn't double-check, but it could be that setting `-e OPENVPN_CONFIG=<something>` sidesteps the issue. Looks like the issue has been present undetected since #1406.

## Logs
```
Starting container with revision: a4d65774f855a04070766e53346661f48c76fa0e
Creating TUN device /dev/net/tun
Using OpenVPN provider: VYPRVPN
Provider VYPRVPN has a custom setup script, executing it
Downloading OpenVPN configs into temporary file /tmp/VyprVPN.zip
Temporarily extracting OpenVPN configs into directory /tmp/tmp.OcDcPi
Removing /tmp/tmp.OcDcPi & /tmp/VyprVPN.zip
No VPN configuration provided. Using default.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Modifying /etc/openvpn/vyprvpn/default.ovpn for best behaviour in this container
Setting OpenVPN credentials...
Fri Dec 18 20:55:44 2020 OpenVPN 2.4.9 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Fri Dec 18 20:55:44 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Fri Dec 18 20:55:44 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Dec 18 20:55:44 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]********
Fri Dec 18 20:55:44 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Dec 18 20:55:44 2020 UDP link local: (not bound)
Fri Dec 18 20:55:44 2020 UDP link remote: [AF_INET]********
Fri Dec 18 20:55:44 2020 TLS: Initial packet from [AF_INET]******** sid=82d09bb9 70d48a72
Fri Dec 18 20:55:44 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Dec 18 20:55:45 2020 VERIFY OK: depth=2, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=Golden Frog GmbH Root CA, emailAddress=admin@goldenfrog.com
Fri Dec 18 20:55:45 2020 VERIFY OK: depth=1, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=VyprVPN Intermediate CA, emailAddress=admin@goldenfrog.com
Fri Dec 18 20:55:45 2020 VERIFY X509NAME OK: C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=mo1.vyprvpn.com, emailAddress=admin@goldenfrog.com
Fri Dec 18 20:55:45 2020 VERIFY OK: depth=0, C=CH, ST=Lucerne, L=Meggen, O=Golden Frog GmbH, CN=mo1.vyprvpn.com, emailAddress=admin@goldenfrog.com
Fri Dec 18 20:55:45 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Dec 18 20:55:45 2020 [mo1.vyprvpn.com] Peer Connection Initiated with [AF_INET]********
Fri Dec 18 20:55:47 2020 SENT CONTROL [mo1.vyprvpn.com]: 'PUSH_REQUEST' (status=1)
Fri Dec 18 20:55:47 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.2.6.1,explicit-exit-notify 5,rcvbuf 524288,route-gateway ********,topology subnet,ping 10,ping-restart 60,ifconfig ******** 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: timers and/or timeouts modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: explicit notify parm(s) modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Fri Dec 18 20:55:47 2020 Socket Buffers: R=[212992->425984] S=[212992->212992]
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: --ifconfig/up options modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: route options modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: route-related options modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: peer-id set
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: adjusting link_mtu to 1625
Fri Dec 18 20:55:47 2020 OPTIONS IMPORT: data channel crypto options modified
Fri Dec 18 20:55:47 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
Fri Dec 18 20:55:47 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Dec 18 20:55:47 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Dec 18 20:55:47 2020 ROUTE_GATEWAY ********/255.255.0.0 IFACE=eth0 HWADDR=********
Fri Dec 18 20:55:47 2020 TUN/TAP device tun0 opened
Fri Dec 18 20:55:47 2020 TUN/TAP TX queue length set to 100
Fri Dec 18 20:55:47 2020 /sbin/ip link set dev tun0 up mtu 1500
Fri Dec 18 20:55:47 2020 /sbin/ip addr add dev tun0 ********/24 broadcast ********
Fri Dec 18 20:55:47 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 ******** 255.255.255.0 init
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Up script executed with tun0 1500 1553 ******** 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : ********
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Updating Transmission settings.json with values from env variables
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 580, in <module>
    main()
  File "/usr/lib/python3.8/site.py", line 563, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.8/site.py", line 464, in venv
    exe_dir, _ = os.path.split(os.path.abspath(executable))
  File "/usr/lib/python3.8/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
sed'ing True to true
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sed: /data/transmission-home/settings.json: No such file or directory

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Transmission startup script complete.
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Fri Dec 18 20:55:47 2020 /sbin/ip route add ********/32 via ********
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Fri Dec 18 20:55:47 2020 /sbin/ip route add 0.0.0.0/1 via ********
Fri Dec 18 20:55:47 2020 /sbin/ip route add ********/1 via ********
Fri Dec 18 20:55:47 2020 Initialization Sequence Completed
```

### Host system:
Irrelevant bur alpine arm64.

**Comment by clement-z** [comment]
Related to #1605
