### ISSUE TITLE
Transmission failing to run after initialization

### ISSUE THREAD

**Issue by GrouchyPanda** [haugene/docker-transmission-openvpn#1881]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```haugene/transmission-openvpn:latest```

*If possible, last working version:* 
 
```haugene/transmission-openvpn:latest```

### Describe the problem

**REQUIRED**
```
I noticed today that the container was unhealthy and began investigating. The web ui was no longer available. I ran through the debug steps and failed at the curl localhost:9091 within the container. The container wasn't updated recently, so not sure if this is an update that NORDVPN has broken, but the cert is succeeding so I'm not sure what it could be. The only error I see is an I/O error after accessing the settings.json.
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
     1) Removed some of the transmission values
     2) Changed release from latest to 3.6
     3) Reset release to latest and ensured that the unraid template hadn't reinserted values (upon update it tends to readd PIA settings even after deletion
     4) Ran the debug steps and failed at curl localhost:9091. Received "curl: (7) Failed to connect to localhost port 9091: Connection refused"
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='transmission' --net='bridge' --privileged=true 
-e TZ="America/Los_Angeles" 
-e HOST_OS="Unraid" 
-e 'OPENVPN_USERNAME'='redacted' 
-e 'OPENVPN_PASSWORD'='redacted' 
-e 'OPENVPN_PROVIDER'='NORDVPN' 
-e 'LOCAL_NETWORK'='192.168.1.0/24' 
-e 'TRANSMISSION_RPC_USERNAME'='admin' 
-e 'TRANSMISSION_RPC_PASSWORD'='password' 
-e 'OPENVPN_OPTS'='--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings' 
-e 'PUID'='99' 
-e 'PGID'='100' 
-e 'TRANSMISSION_DOWNLOAD_DIR'='/downloads/completed' 
-e 'TRANSMISSION_RPC_AUTHENTICATION_REQUIRED'='true' 
-e 'TRANSMISSION_RATIO_LIMIT_ENABLED'='true' 
-e 'TRANSMISSION_DOWNLOAD_QUEUE_SIZE'='10' 
-e 'TRANSMISSION_CACHE_SIZE_MB'='10' 
-e 'TRANSMISSION_INCOMPLETE_DIR'='/downloads/incomplete' 
-e 'TRANSMISSION_WEB_UI'='combustion' 
-e 'GLOBAL_APPLY_PERMISSIONS'='true' 
-e 'WEBPROXY_ENABLED'='false'
-e 'NORDVPN_CATEGORY'='legacy_p2p' 
-e 'NORDVPN_PROTOCOL'='tcp' 
-e 'NORDVPN_COUNTRY'='US' 
-p '9091:9091/tcp' 
-v '/mnt/user/downloads':'/data':'rw' 
-v '/mnt/user/downloads/':'/downloads':'rw' 
-v '/mnt/user/downloads/watch/':'/watch':'rw' 
-v '/mnt/user/downloads/':'/mnt/user/T_Media/Torrent/':'rw' 
--cap-add=NET_ADMIN 
--restart=always 
--log-opt max-size=50m --log-driver json-file --dns 8.8.8.8 --dns 1.1.1.1 
'haugene/transmission-openvpn:latest'
b0d292df588013fb34419d615d2b4b0aed8b2f532f6643ac78e01bf61eab36bd
```

### Logs

 

**REQUIRED**
```txt
ErrorWarningSystemArrayLogin


Starting container with revision: 73ec516cc246972289c7b96ffa88c81e037fe364
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: NORDVPN
Provider NORDVPN has a custom setup script, executing it
2021-07-19 21:48:19 Checking curl installation
2021-07-19 21:48:19 Removing existing configs
2021-07-19 21:48:19 Selecting the best server...
2021-07-19 21:48:19 Searching for technology: openvpn_tcp
2021-07-19 21:48:19 Best server : us8605.nordvpn.com
2021-07-19 21:48:19 Downloading config: default.ovpn
2021-07-19 21:48:19 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us8605.nordvpn.com.tcp.ovpn
2021-07-19 21:48:19 Selecting the best server...
2021-07-19 21:48:19 Searching for country : US (228)
2021-07-19 21:48:19 Searching for technology: openvpn_tcp
2021-07-19 21:48:19 Best server : us8605.nordvpn.com
2021-07-19 21:48:19 Downloading config: us8605.nordvpn.com.ovpn
2021-07-19 21:48:19 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us8605.nordvpn.com.tcp.ovpn
Starting OpenVPN using config us8605.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/us8605.nordvpn.com.ovpn for best behaviour in this container
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
2021-07-19 21:48:21 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.

2021-07-19 21:48:21 OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May 4 2021
2021-07-19 21:48:21 library versions: OpenSSL 1.1.1k 25 Mar 2021, LZO 2.10
2021-07-19 21:48:21 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-07-19 21:48:21 NOTE: --fast-io is disabled since we are not using UDP
2021-07-19 21:48:21 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2021-07-19 21:48:21 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2021-07-19 21:48:21 TCP/UDP: Preserving recently used remote address: [AF_INET]193.160.245.99:443
2021-07-19 21:48:21 Socket Buffers: R=[87380->87380] S=[65536->65536]
2021-07-19 21:48:21 Attempting to establish TCP connection with [AF_INET]193.160.245.99:443 [nonblock]
2021-07-19 21:48:22 TCP connection established with [AF_INET]193.160.245.99:443
2021-07-19 21:48:22 TCP_CLIENT link local: (not bound)
2021-07-19 21:48:22 TCP_CLIENT link remote: [AF_INET]193.160.245.99:443
2021-07-19 21:48:22 TLS: Initial packet from [AF_INET]193.160.245.99:443, sid=d03a8f28 ea4760b8
2021-07-19 21:48:23 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
2021-07-19 21:48:23 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA6
2021-07-19 21:48:23 VERIFY KU OK
2021-07-19 21:48:23 Validating certificate extended key usage
2021-07-19 21:48:23 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2021-07-19 21:48:23 VERIFY EKU OK
2021-07-19 21:48:23 VERIFY OK: depth=0, CN=us8605.nordvpn.com
2021-07-19 21:48:23 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA512
2021-07-19 21:48:23 [us8605.nordvpn.com] Peer Connection Initiated with [AF_INET]193.160.245.99:443
2021-07-19 21:48:24 SENT CONTROL [us8605.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2021-07-19 21:48:25 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.2.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.2.2 255.255.255.0,peer-id 0,cipher AES-256-GCM'
2021-07-19 21:48:25 OPTIONS IMPORT: timers and/or timeouts modified
2021-07-19 21:48:25 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp
2021-07-19 21:48:25 OPTIONS IMPORT: compression parms modified
2021-07-19 21:48:25 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
2021-07-19 21:48:25 Socket Buffers: R=[87380->1048576] S=[130560->1048576]
2021-07-19 21:48:25 OPTIONS IMPORT: --ifconfig/up options modified
2021-07-19 21:48:25 OPTIONS IMPORT: route options modified
2021-07-19 21:48:25 OPTIONS IMPORT: route-related options modified
2021-07-19 21:48:25 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2021-07-19 21:48:25 OPTIONS IMPORT: peer-id set
2021-07-19 21:48:25 OPTIONS IMPORT: adjusting link_mtu to 1659
2021-07-19 21:48:25 OPTIONS IMPORT: data channel crypto options modified
2021-07-19 21:48:25 Data Channel: using negotiated cipher 'AES-256-GCM'
2021-07-19 21:48:25 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2021-07-19 21:48:25 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2021-07-19 21:48:25 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:09
2021-07-19 21:48:25 TUN/TAP device tun0 opened
2021-07-19 21:48:25 /sbin/ip link set dev tun0 up mtu 1500
2021-07-19 21:48:25 /sbin/ip link set dev tun0 up
2021-07-19 21:48:25 /sbin/ip addr add dev tun0 10.7.2.2/24
2021-07-19 21:48:25 /etc/openvpn/tunnelUp.sh tun0 1500 1587 10.7.2.2 255.255.255.0 init
Up script executed with tun0 1500 1587 10.7.2.2 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.2.2
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Traceback (most recent call last):
File "/etc/transmission/updateSettings.py", line 45, in <module>
settings_dict = json.load(input_file)
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
OSError: [Errno 5] I/O error

2021-07-19 21:48:25 /sbin/ip route add 193.160.245.99/32 via 172.17.0.1
2021-07-19 21:48:25 /sbin/ip route add 0.0.0.0/1 via 10.7.2.1
2021-07-19 21:48:25 /sbin/ip route add 128.0.0.0/1 via 10.7.2.1
2021-07-19 21:48:25 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

2021-07-19 21:48:25 Initialization Sequence Completed
```

### Host system

**REQUIRED**
```txt
Unraid v6.9.1 Docker version 19.03.14
```

**Comment by pkishino** [comment]
Hmm, possibly your settings file is corrupted and/or done reading issue. Can you manually check the file if it’s ok and no strange value ? 
or try deleting it and restart

**Comment by GrouchyPanda** [comment]
So in looking more to see if that file was locked, it appears unraid deleted the share that was on. Thank you for the prod to look in the right place. Closing issue now as its not a docker issue.
